version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - app_poetry:/root/.cache/pypoetry
    tty: true
    environment:
      PYTHONPATH: /app
      PYTHONDONTWRITEBYTECODE: 1
    command: bash -c "poetry install; /bin/bash"

volumes:
  app_poetry:
    external: false
